version: "2"

volumes:
  nodered:

services:

  mosquitto:
    image: arm32v6/eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"

  node-red:
    build: ./node-red
    depends_on:
      - mosquitto
    volumes:
      - 'nodered:/data'
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - "80:80"
